spring.application.name=dziekanat

# H2 in-memory database
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dziekanatdb

# JPA - automatyczne tworzenie tabel z encji
spring.jpa.defer-datasource-initialization=true

# Opcjonalnie - pokazuje SQL w konsoli (przydatne do debugowania)
spring.jpa.show-sql=true