-- Przedmioty
INSERT INTO SUBJECT(ID, NAME, ECTS, SEMESTER_NUMBER) VALUES(1, 'Amial', 5, 1);
INSERT INTO SUBJECT(ID, NAME, ECTS, SEMESTER_NUMBER) VALUES(2, 'Fizyka', 4, 1);
INSERT INTO SUBJECT(ID, NAME, ECTS, SEMESTER_NUMBER) VALUES(3, 'Programowanie komputerów', 6, 2);
INSERT INTO SUBJECT(ID, NAME, ECTS, SEMESTER_NUMBER) VALUES(4, 'Bazy danych', 5, 3);

ALTER SEQUENCE SUBJECT_SEQ RESTART WITH (SELECT MAX(ID) + 1 FROM SUBJECT);